package tdl.demo.service;

import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import tdl.demo.enumerator.Status;
import tdl.demo.exceptions.TaskNotFoundException;
import tdl.demo.model.Task;
import tdl.demo.repository.TaskRepository;

import java.util.List;

//
@Service
@RequiredArgsConstructor
public class TaskService {

    private final TaskRepository taskRepository;

    // Create task:
    public Task createTask(Task task) {
        return taskRepository.save(task); // .save() is a JpaRepository method
    }

    // NOTE: Most of the read logic is automatically generated by JpaRepository
    // Get all tasks:
    public List<Task> getAllTasks() {
        return taskRepository.findAll();
    }

    // Get tasks by status:
    public List<Task> getTasksByStatus(Status status) {
        return taskRepository.findByStatus(status);
    }


    // NOTE: Individual update methods may be used for a button, whereas the all encompassing updateTask method is for full task updates
    // Mark task as complete:
    public Task markComplete(Long id) {
        Task task = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        task.setStatus(Status.COMPLETED);
        return taskRepository.save(task);
    }

    // Mark task as ongoing:
    public Task markOngoing(Long id) {
        Task task = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        task.setStatus(Status.ONGOING);
        return taskRepository.save(task);
    }

    // Mark task as suspended:
    public Task markSuspended(Long id) {
        Task task = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        task.setStatus(Status.SUSPENDED);
        return taskRepository.save(task);
    }


    // Update task: (null checks prevent wiping unchanged fields)
    public Task updateTask(Long id, Task updated) {
        Task existing = taskRepository.findById(id).orElseThrow(() -> new TaskNotFoundException("Task not found"));
        if (updated.getTitle() != null) {
            existing.setTitle(updated.getTitle());
        }
        if (updated.getDescription() != null) {
            existing.setDescription(updated.getDescription());
        }
        if (updated.getStatus() != null) {
            existing.setStatus(updated.getStatus());
        }
        if (updated.getPriority() != null) {
            existing.setPriority(updated.getPriority());
        }
        if (updated.getDueDate() != null) {
            existing.setDueDate(updated.getDueDate());
        }

        return taskRepository.save(existing);
    }


    // NOTE: Add confirmation logic before deletion
    // Delete task: (by id)
    public void deleteTask(Long id) {
        taskRepository.deleteById(id);
    }



    // Sort by methods: (Spring auto-generates by deriving query from name)
    public List<Task> getAndSortAllTasks(String sortBy) {
        // Uses the SpringData Sort class to sort by a given property (String sortBy )
        return taskRepository.findAll(Sort.by(sortBy));
    }

}